### ISSUE TITLE
New Error - compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync('BaseHrefWebpackPlugin

### ISSUE THREAD

**Issue by subramn** [dzonatan/base-href-webpack-plugin#10]
Hi,

Recently i started receiving the following error
compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync('BaseHrefWebpackPlugin', function (data,
callback)
TypeError: Cannot read property 'tapAsync' of undefined

I am using 
"html-webpack-plugin": "4.0.0-alpha.1",
	"base-href-webpack-plugin": "^2.0.0",
suddenly when i refreshed package.json started getting the above error

any help

**Comment by RuslanKurtianyk** [comment]
Hi, any updates?

**Comment by dzonatan** [comment]
You forgot to install/use `html-webpack-plugin` which is mandatory for this plugin to work.
