### ISSUE TITLE
Support html-webpack-plugin 4.x

### ISSUE THREAD

**Issue by krusche** [dzonatan/base-href-webpack-plugin#12]
Error message: Cannot read property 'tapAsync' of undefined

Also see https://github.com/jantimon/html-webpack-plugin/issues/1377

**Comment by drugoi** [comment]
Hey, @krusche, why are you using this plugin?

I mean, HtmlWebpackPlugin has support for base tag starting from 4.0.0 version — https://github.com/jantimon/html-webpack-plugin/pull/1160

So, probably, base-href-webpack-plugin is only helpful for versions less than 4.0.0.

**Comment by krusche** [comment]
I noticed this as well and removed it
