### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by DmitryShostak** [dzonatan/base-href-webpack-plugin#14]
`compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync('BaseHrefWebpackPlugin', (data, callback) => {
TypeError: Cannot read property 'tapAsync' of undefined`

Has anyone solved this issue yet?

    "webpack": "^5.22.0",
    "html-webpack-plugin": "^5.1.0",

**Comment by dzonatan** [comment]
`v3.0.0` was released for webpack v5.
