### ISSUE TITLE
Support html-webpack-plugin 5.x

### ISSUE THREAD

**Issue by JarynChen** [dzonatan/base-href-webpack-plugin#21]
In npm8, if I depend on html-webpack-plugin 5.x, it will prompt Conflicting peer dependency, so I hope peer dependency can support 5.x
![image](https://user-images.githubusercontent.com/41881490/151745751-ae792e9d-cf1f-4230-bdb7-b9a1da4e5460.png)

**Comment by dzonatan** [comment]
Is this plugin still beneficial for you? Have you tried using https://github.com/jantimon/html-webpack-plugin#base-tag option that is natively supported by `HtmlWebpackPlugin` since v4?

**Comment by JarynChen** [comment]
> Is this plugin still beneficial for you? Have you tried using https://github.com/jantimon/html-webpack-plugin#base-tag option that is natively supported by `HtmlWebpackPlugin` since v4?

Hello, thank you for your reply, what I mean is that it is not a problem of use, but a problem of the dependent version in your plugin. The html-webpack-plugin has been officially upgraded to version 5.x, so I hope you can upgrade the dependencies in base-href-webpack-plugin

**Comment by dzonatan** [comment]
I know but there was a question raised in #22 if this library is still relevant. Perhaps you don't need it too so you could drop this dependency altogether.

**Comment by JarynChen** [comment]
> I know but there was a question raised in #22 if this library is still relevant. Perhaps you don't need it too so you could drop this dependency altogether.

Hi, thanks for your reply, I just saw this message, I will try to replace all to html-webpack-plugin, thank you very much for your contribution
