### ISSUE TITLE
TypeError: baseHrefWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by alexandrbig** [dzonatan/base-href-webpack-plugin#5]
Hello.
I am trying to add the plugin to react project, but face an error:
```
[1]         new BaseHrefWebpackPlugin({ baseHref: process.env.BASE_HREF }),
[1]         ^
[1] 
[1] TypeError: BaseHrefWebpackPlugin is not a constructor
```
"base-href-webpack-plugin": "^1.0.2",
"webpack": "1.12.15",

Also tried here:
https://npm.runkit.com/base-href-webpack-plugin
```
const baseHrefWebpackPlugin = require("base-href-webpack-plugin");

new baseHrefWebpackPlugin({ baseHref: '/' })
```

Screenshot: 
https://www.screencast.com/t/Rctm0JPH2

What am I doing wrong?
Thank you.

**Comment by dzonatan** [comment]
You missed [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) from example. 

You can use either with object descrution:
```js
const { BaseHrefWebpackPlugin } = require("base-href-webpack-plugin");
```

Or without:
```js
const plugin = require("base-href-webpack-plugin");
new plugin.BaseHrefWebpackPlugin({ baseHref: '/' })
```
