### ISSUE TITLE
Support for Webpack 4

### ISSUE THREAD

**Issue by andyrichardson** [dzonatan/base-href-webpack-plugin#6]
**Description**
webpack-dev-server 3.0.0 / webpack 4.0 is failing to build while using this plugin.

**Log**

    Error: Plugin could not be registered at 'html-webpack-plugin-before-html-process
    ing'. Hook was not found.    
                                                    
    BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compati$
    lity layer for this hook, hook into 'this._pluginCompat'.      
                  
    at Compilation.plugin (/home/arichardson/development/sonata-web-client/node_m
    odules/webpack/node_modules/tapable/lib/Tapable.js:63:9)

    at Compilation.deprecated [as plugin] (internal/util.js:53:15)

    at /home/arichardson/development/sonata-web-client/node_modules/base-href-web
    pack-plugin/build/index.js:28:21

**Comment by dzonatan** [comment]
Fixed with v2.0.0.
